### ISSUE TITLE
Dont work anymore.

### ISSUE THREAD

**Issue by ayarrus** [JFCodes/WhatsAppJS#5]
Error:

(node:16216) UnhandledPromiseRejectionWarning: Error: WhatsAppJS is already logged in. Cannot generate QRCode.
    at WhatsAppJs.<anonymous> (C:\Users\Fox\Desktop\wp test\WhatsAppJS-master\WhatsAppJs\WhatsAppJs.js:103:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Fox\Desktop\wp test\WhatsAppJS-master\WhatsAppJs\WhatsAppJs.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16216) UnhandledPromiseRejectionWarning: Error: Failed to send message
    at newMessage.send.catch (C:\Users\Fox\Desktop\wp test\WhatsAppJS-master\WhatsAppJs\WhatsAppJs.js:136:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Image:
![xxxx](https://user-images.githubusercontent.com/10744797/61835659-1cc98c00-ae53-11e9-8546-f263eba58981.png)

**Comment by JFCodes** [comment]
After a long time I am picking this one up again.
Removing outdated issues.
